In [2]:
import numpy as np

In [3]:
mat = np.array([[1,2],[3,4]])

mat

array([[1, 2],
       [3, 4]])

In [4]:
np.linalg.det(mat)     # determinant using linear algebra under numpy

-2.0000000000000004

In [5]:
np.linalg.inv(mat)      # inverse

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [6]:
mat.transpose()

array([[1, 3],
       [2, 4]])

In [7]:
np.trace(mat)     # sum of diagonal values

5

In [8]:
mat2 = np.array([[5,6],[7,8]])

In [9]:
mat * mat2              # multiplication of corresponding values of the array

array([[ 5, 12],
       [21, 32]])

In [10]:
mat.dot(mat2)           # multiplication of two arrays/ matrics

array([[19, 22],
       [43, 50]])

# Linear Algebra equations

# suppose we have two equations i.e.

### 2x + y = 1
### x + y = 2

In [11]:
M0 = np.array([[2,1],[1,1]])     # left hand side values stored in M0

M1 = np.array([1,2])            # right hand side values stored in M1

In [12]:
np.linalg.solve(M0, M1)         # values for X and Y

array([-1.,  3.])

# Eigen Values & Eigen Vectors

In [14]:
eigvalues , eigvectors = np.linalg.eig(mat)

In [15]:
eigvalues

array([-0.37228132,  5.37228132])

In [16]:
eigvectors

array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]])