In [1]:
import numpy as np

a = np.random.random(size = (3,3))
b= np.random.random(size = (3,3))

In [2]:
a

array([[0.28579822, 0.90745812, 0.51324599],
       [0.67713755, 0.87411529, 0.41280163],
       [0.95951887, 0.07110941, 0.0815439 ]])

In [3]:
b

array([[0.24451756, 0.65353689, 0.73486483],
       [0.99594467, 0.55851437, 0.12945481],
       [0.19816412, 0.71980297, 0.68550379]])

In [ ]:
# horizontal Stack

In [4]:
c = np.hstack((a,b))

In [5]:
c

array([[0.28579822, 0.90745812, 0.51324599, 0.24451756, 0.65353689,
        0.73486483],
       [0.67713755, 0.87411529, 0.41280163, 0.99594467, 0.55851437,
        0.12945481],
       [0.95951887, 0.07110941, 0.0815439 , 0.19816412, 0.71980297,
        0.68550379]])

In [6]:
d = np.vstack((a,b))

In [7]:
d

array([[0.28579822, 0.90745812, 0.51324599],
       [0.67713755, 0.87411529, 0.41280163],
       [0.95951887, 0.07110941, 0.0815439 ],
       [0.24451756, 0.65353689, 0.73486483],
       [0.99594467, 0.55851437, 0.12945481],
       [0.19816412, 0.71980297, 0.68550379]])

In [8]:
a = 10 * a

In [12]:
a

array([[2.85798219, 9.07458124, 5.13245988],
       [6.77137554, 8.74115293, 4.12801631],
       [9.59518874, 0.71109406, 0.815439  ]])

In [11]:
np.floor(a)

array([[2., 9., 5.],
       [6., 8., 4.],
       [9., 0., 0.]])

In [13]:
np.ceil(a)

array([[ 3., 10.,  6.],
       [ 7.,  9.,  5.],
       [10.,  1.,  1.]])

In [14]:
np.sum(a)

47.827289899546756

In [15]:
np.sum(a, axis = 0)          # add all the elements coloumn wise

array([19.22454648, 18.52682823, 10.07591519])

In [16]:
np.sum(a, axis = 1)          # add all the elements row wise

array([17.06502332, 19.64054478, 11.1217218 ])

In [17]:
np.mean(a)

5.314143322171862

In [18]:
np.cumsum(a)                  # cummulative sum

array([ 2.85798219, 11.93256344, 17.06502332, 23.83639886, 32.57755179,
       36.7055681 , 46.30075684, 47.0118509 , 47.8272899 ])

In [19]:
np.cumproduct(a)

array([2.85798219e+00, 2.59349916e+01, 1.33110304e+02, 9.01339857e+02,
       7.87874953e+03, 3.25236065e+04, 3.12070143e+05, 2.21911225e+05,
       1.80955068e+05])

In [20]:
e = [1,2,3,4,4,5,6,7,3,1,9,7]

In [21]:
np.unique(e)                     # unique elements

array([1, 2, 3, 4, 5, 6, 7, 9])

In [23]:
np.min(a)

0.7110940594296911

In [24]:
np.max(a)

9.595188741475887

In [25]:
for item in a:
    print(item)

[2.85798219 9.07458124 5.13245988]
[6.77137554 8.74115293 4.12801631]
[9.59518874 0.71109406 0.815439  ]


In [26]:
for index, item in enumerate(a):
    print(index, item)

0 [2.85798219 9.07458124 5.13245988]
1 [6.77137554 8.74115293 4.12801631]
2 [9.59518874 0.71109406 0.815439  ]
