# Numpy

Numpy is Linear algebara, Matrix manipulation library. Every major Data science related library writtern on top of numpy.

Doc : https://docs.scipy.org/doc/numpy-1.10.1/user/whatisnumpy.html

* pip install numpy
* conda install numpy

* Creating array
* attributes , methods on array
* selection and indexing
* operation

In [2]:
import numpy as np

In [3]:
lst = [2, 5 ,7,8]

In [4]:
np.array(lst)

array([2, 5, 7, 8])

In [5]:
np.array([lst, lst])

array([[2, 5, 7, 8],
       [2, 5, 7, 8]])

In [5]:
np.array([ [2, 4, 6], [2, 7, 9]  ])

array([[2, 4, 6],
       [2, 7, 9]])

In [6]:
np.array([ [2, 4, 6], [2, 7, 9], [3, -1, 6]  ])

array([[ 2,  4,  6],
       [ 2,  7,  9],
       [ 3, -1,  6]])

In [1]:
# eye will create a matrix with diagonal values = 1

In [8]:
10 * np.eye(4)

array([[10.,  0.,  0.,  0.],
       [ 0., 10.,  0.,  0.],
       [ 0.,  0., 10.,  0.],
       [ 0.,  0.,  0., 10.]])

In [9]:
0 * np.eye(4)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
np.zeros(shape=(4, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [12]:
5 * np.ones(shape=(3, 5))

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [13]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(-5, 10)

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [15]:
np.arange(-5, 10, 3)

array([-5, -2,  1,  4,  7])

In [16]:
np.arange(100, 10, -5)

array([100,  95,  90,  85,  80,  75,  70,  65,  60,  55,  50,  45,  40,
        35,  30,  25,  20,  15])

In [6]:
# to show the equal partitions between start ans stop values

In [17]:
np.linspace(0, 20, 20)

array([ 0.        ,  1.05263158,  2.10526316,  3.15789474,  4.21052632,
        5.26315789,  6.31578947,  7.36842105,  8.42105263,  9.47368421,
       10.52631579, 11.57894737, 12.63157895, 13.68421053, 14.73684211,
       15.78947368, 16.84210526, 17.89473684, 18.94736842, 20.        ])

In [18]:
np.linspace(0, 20, 5)

array([ 0.,  5., 10., 15., 20.])

In [19]:
np.random.rand(2,3)

array([[0.17623543, 0.84431091, 0.38561783],
       [0.28729748, 0.52275462, 0.90935495]])

In [20]:
np.random.rand(2,3 , 6)

array([[[0.39001359, 0.32870421, 0.78721091, 0.8925651 , 0.94380589,
         0.47477441],
        [0.90677138, 0.39718662, 0.84258692, 0.21240525, 0.00315681,
         0.2665376 ],
        [0.60989939, 0.69432754, 0.98871569, 0.45422531, 0.18422505,
         0.79690951]],

       [[0.21426401, 0.58107988, 0.367783  , 0.33415494, 0.04369496,
         0.84936196],
        [0.97880772, 0.46676014, 0.18455763, 0.39959901, 0.74582268,
         0.02834678],
        [0.91963749, 0.28301464, 0.02845203, 0.18952338, 0.00102623,
         0.84356878]]])

In [21]:
np.random.randn(4,5)

array([[ 1.4939586 , -0.94083558, -0.54225579, -0.83406616, -0.26032042],
       [ 0.48166028,  0.70117099, -0.35431488,  0.77774953,  0.85114757],
       [ 1.49262322,  0.67074908, -0.51007037,  1.49030206, -0.1509519 ],
       [ 1.22980963, -1.70204292, -0.83984181,  0.52511116, -0.83645005]])

In [28]:
np.random.randint(10, 50, 5)

array([47, 11, 26, 14, 21])

In [29]:
mat = np.random.randn(4,5)

In [30]:
mat

array([[ 0.54248691, -0.57599021, -0.01474314, -1.41767914,  1.47493301],
       [ 0.01868561, -3.04906268, -0.06408717,  0.88525694,  0.84894607],
       [-0.05094353,  1.19257418,  0.17410278,  0.13927718,  0.081297  ],
       [-1.12459009, -1.53692172,  0.63617614,  0.51094818,  1.6019199 ]])

In [31]:
type(mat)

numpy.ndarray

In [32]:
mat.size

20

In [33]:
mat.shape

(4, 5)

In [35]:
mat.reshape(2,10).shape

(2, 10)

In [37]:
mat.reshape(3,10)

ValueError: cannot reshape array of size 20 into shape (3,10)

In [38]:
mat.dtype

dtype('float64')

In [39]:
arr = np.arange(50,70)

In [40]:
arr

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69])

In [41]:
arr.shape

(20,)

In [42]:
arr[4]

54

In [43]:
arr[18]

68

In [ ]:
#arr[star : end]

In [45]:
arr[8 : 20] 

array([58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [46]:
arr[8 : ]

array([58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [47]:
arr

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69])

In [48]:
arr[0: 5]

array([50, 51, 52, 53, 54])

In [49]:
arr[ : 5]

array([50, 51, 52, 53, 54])

In [51]:
arr[ : 7]

array([50, 51, 52, 53, 54, 55, 56])

In [52]:
arr[-1]

69

In [53]:
arr[-2]

68

In [54]:
arr

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69])

In [56]:
sum(arr > 55)

14

In [57]:
arr + 100

array([150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162,
       163, 164, 165, 166, 167, 168, 169])

In [58]:
arr - 20

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49])

In [59]:
arr * 2

array([100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124,
       126, 128, 130, 132, 134, 136, 138])

In [60]:
arr / 2

array([25. , 25.5, 26. , 26.5, 27. , 27.5, 28. , 28.5, 29. , 29.5, 30. ,
       30.5, 31. , 31.5, 32. , 32.5, 33. , 33.5, 34. , 34.5])

In [62]:
mat = np.random.rand(5,5)

In [63]:
mat

array([[0.26310501, 0.1899667 , 0.72366052, 0.26226433, 0.67339029],
       [0.41022105, 0.78275212, 0.66441636, 0.66036598, 0.21330877],
       [0.86833902, 0.26569716, 0.29897834, 0.21147839, 0.17187017],
       [0.50488167, 0.14839601, 0.15808434, 0.56778525, 0.06930502],
       [0.55792591, 0.25129129, 0.91327813, 0.11249826, 0.98907252]])

In [ ]:
mat[ row , column ]

In [64]:
mat[0 , 0 ]

0.26310501487446625

In [65]:
mat[3,2]

0.15808434322930964

In [66]:
mat[1,  ]

array([0.41022105, 0.78275212, 0.66441636, 0.66036598, 0.21330877])

In [70]:
mat[ :, 4 ]

array([0.67339029, 0.21330877, 0.17187017, 0.06930502, 0.98907252])

In [71]:
mat[1: 4, :]

array([[0.41022105, 0.78275212, 0.66441636, 0.66036598, 0.21330877],
       [0.86833902, 0.26569716, 0.29897834, 0.21147839, 0.17187017],
       [0.50488167, 0.14839601, 0.15808434, 0.56778525, 0.06930502]])

In [72]:
mat

array([[0.26310501, 0.1899667 , 0.72366052, 0.26226433, 0.67339029],
       [0.41022105, 0.78275212, 0.66441636, 0.66036598, 0.21330877],
       [0.86833902, 0.26569716, 0.29897834, 0.21147839, 0.17187017],
       [0.50488167, 0.14839601, 0.15808434, 0.56778525, 0.06930502],
       [0.55792591, 0.25129129, 0.91327813, 0.11249826, 0.98907252]])

In [73]:
mat[:, 0:2]

array([[0.26310501, 0.1899667 ],
       [0.41022105, 0.78275212],
       [0.86833902, 0.26569716],
       [0.50488167, 0.14839601],
       [0.55792591, 0.25129129]])

In [ ]:
1,2 row
0, 1 column

In [74]:
mat[1: 3, 0 : 2]

array([[0.41022105, 0.78275212],
       [0.86833902, 0.26569716]])

In [75]:
arr

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69])

In [76]:
np.cos(arr)

array([ 0.96496603,  0.7421542 , -0.16299078, -0.91828279, -0.82930983,
        0.02212676,  0.85322011,  0.89986683,  0.11918014, -0.77108022,
       -0.95241298, -0.25810164,  0.67350716,  0.98589658,  0.39185723,
       -0.56245385, -0.99964746, -0.5177698 ,  0.44014302,  0.99339038])

In [77]:
np.tan(arr)

array([-2.71900612e-01,  9.03086149e-01, -6.05327238e+00, -4.31158197e-01,
        6.73800101e-01, -4.51830879e+01, -6.11273688e-01,  4.84699227e-01,
        8.33085685e+00, -8.25774009e-01,  3.20040389e-01,  3.74316794e+00,
       -1.09750978e+00,  1.69749752e-01,  2.34786031e+00, -1.47003826e+00,
        2.65605178e-02,  1.65231726e+00, -2.04008160e+00, -1.15548546e-01])

In [79]:
np.sum(arr)

1190

In [80]:
np.mean(arr)

59.5